//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.ProjectModel {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stride.Core.NuGet.NuGet.ProjectModel.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argument cannot be null or empty..
        /// </summary>
        internal static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid dependency target value &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidDependencyTarget {
            get {
                return ResourceManager.GetString("InvalidDependencyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The pack options package type must be a string or array of strings in &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidPackageType {
            get {
                return ResourceManager.GetString("InvalidPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading lock file &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string Log_ErrorReadingLockFile {
            get {
                return ResourceManager.GetString("Log_ErrorReadingLockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string Log_ErrorReadingProjectJson {
            get {
                return ResourceManager.GetString("Log_ErrorReadingProjectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading &apos;{0}&apos; at line {1} column {2} : {3}.
        /// </summary>
        internal static string Log_ErrorReadingProjectJsonWithLocation {
            get {
                return ResourceManager.GetString("Log_ErrorReadingProjectJsonWithLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imports contains an invalid framework: &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string Log_InvalidImportFramework {
            get {
                return ResourceManager.GetString("Log_InvalidImportFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problem reading the cache file {0} : {1}.
        /// </summary>
        internal static string Log_ProblemReadingCacheFile {
            get {
                return ResourceManager.GetString("Log_ProblemReadingCacheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve tool &apos;&apos;..
        /// </summary>
        internal static string MissingToolName {
            get {
                return ResourceManager.GetString("MissingToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package dependencies must specify a version range..
        /// </summary>
        internal static string MissingVersionOnDependency {
            get {
                return ResourceManager.GetString("MissingVersionOnDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools must specify a version range..
        /// </summary>
        internal static string MissingVersionOnTool {
            get {
                return ResourceManager.GetString("MissingVersionOnTool", resourceCulture);
            }
        }
    }
}
