//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.PackageManagement {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stride.Core.NuGet.NuGet.PackageManagement.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added package &apos;{0}&apos; to folder &apos;{1}&apos;.
        /// </summary>
        internal static string AddedPackageToFolder {
            get {
                return ResourceManager.GetString("AddedPackageToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added package &apos;{0}&apos; to folder &apos;{1}&apos; from source &apos;{2}&apos;.
        /// </summary>
        internal static string AddedPackageToFolderFromSource {
            get {
                return ResourceManager.GetString("AddedPackageToFolderFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added package &apos;{0}&apos; to project &apos;{1}&apos;.
        /// </summary>
        internal static string AddedPackageToMSBuildProject {
            get {
                return ResourceManager.GetString("AddedPackageToMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added package &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string AddedPackageToPackagesConfig {
            get {
                return ResourceManager.GetString("AddedPackageToPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding package &apos;{0}&apos; to folder &apos;{1}&apos;.
        /// </summary>
        internal static string AddingPackageToFolder {
            get {
                return ResourceManager.GetString("AddingPackageToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding package &apos;{0}&apos; to project &apos;{1}&apos;.
        /// </summary>
        internal static string AddingPackageToMSBuildProject {
            get {
                return ResourceManager.GetString("AddingPackageToMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding package &apos;{0}&apos;, which only has dependencies, to project &apos;{1}&apos;..
        /// </summary>
        internal static string AddingPackageWithOnlyDependencies {
            get {
                return ResourceManager.GetString("AddingPackageWithOnlyDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding package &apos;{0}&apos;, which only has tools group, to project &apos;{1}&apos;.
        /// </summary>
        internal static string AddingPackageWithOnlyToolsGroup {
            get {
                return ResourceManager.GetString("AddingPackageWithOnlyToolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Another NuGetProject with the same name &apos;{0}&apos; exists in solution.
        /// </summary>
        internal static string AnotherNuGetProjectWithSameNameExistsInSolution {
            get {
                return ResourceManager.GetString("AnotherNuGetProjectWithSameNameExistsInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argument cannot be null or empty.
        /// </summary>
        internal static string Argument_Cannot_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value must be greater than or equal to {0}.
        /// </summary>
        internal static string Argument_Must_Be_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Argument_Must_Be_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempting to gather dependency information for package &apos;{0}&apos; with respect to project &apos;{1}&apos;, targeting &apos;{2}&apos;.
        /// </summary>
        internal static string AttemptingToGatherDependencyInfo {
            get {
                return ResourceManager.GetString("AttemptingToGatherDependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempting to gather dependency information for multiple packages with respect to project &apos;{0}&apos;, targeting &apos;{1}&apos;.
        /// </summary>
        internal static string AttemptingToGatherDependencyInfoForMultiplePackages {
            get {
                return ResourceManager.GetString("AttemptingToGatherDependencyInfoForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempting to resolve dependencies for package &apos;{0}&apos; with DependencyBehavior &apos;{1}&apos;.
        /// </summary>
        internal static string AttemptingToResolveDependencies {
            get {
                return ResourceManager.GetString("AttemptingToResolveDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempting to resolve dependencies for multiple packages..
        /// </summary>
        internal static string AttemptingToResolveDependenciesForMultiplePackages {
            get {
                return ResourceManager.GetString("AttemptingToResolveDependenciesForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package restore failed for &apos;{0}&apos;..
        /// </summary>
        internal static string BuildIntegratedPackageRestoreFailed {
            get {
                return ResourceManager.GetString("BuildIntegratedPackageRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restoring packages for &apos;{0}&apos;..
        /// </summary>
        internal static string BuildIntegratedPackageRestoreStarted {
            get {
                return ResourceManager.GetString("BuildIntegratedPackageRestoreStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package restore completed successfully for &apos;{0}&apos;..
        /// </summary>
        internal static string BuildIntegratedPackageRestoreSucceeded {
            get {
                return ResourceManager.GetString("BuildIntegratedPackageRestoreSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content files should not be target framework specific, whereas, &apos;{0}&apos; is.
        /// </summary>
        internal static string ContentFilesShouldNotBeTargetFrameworkSpecific {
            get {
                return ResourceManager.GetString("ContentFilesShouldNotBeTargetFrameworkSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added file &apos;{0}&apos;..
        /// </summary>
        internal static string Debug_AddedFile {
            get {
                return ResourceManager.GetString("Debug_AddedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added file &apos;{0}&apos; to folder &apos;{1}&apos;..
        /// </summary>
        internal static string Debug_AddedFileToFolder {
            get {
                return ResourceManager.GetString("Debug_AddedFileToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed file &apos;{0}&apos;..
        /// </summary>
        internal static string Debug_RemovedFile {
            get {
                return ResourceManager.GetString("Debug_RemovedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed file &apos;{0}&apos; from folder &apos;{1}&apos;..
        /// </summary>
        internal static string Debug_RemovedFileFromFolder {
            get {
                return ResourceManager.GetString("Debug_RemovedFileFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed folder &apos;{0}&apos;..
        /// </summary>
        internal static string Debug_RemovedFolder {
            get {
                return ResourceManager.GetString("Debug_RemovedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; {0} are being added from &apos;{1}&apos;{2}.
        /// </summary>
        internal static string Debug_TargetFrameworkInfo {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assembly references.
        /// </summary>
        internal static string Debug_TargetFrameworkInfo_AssemblyReferences {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_AssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build files.
        /// </summary>
        internal static string Debug_TargetFrameworkInfo_BuildFiles {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_BuildFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content files.
        /// </summary>
        internal static string Debug_TargetFrameworkInfo_ContentFiles {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_ContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (not framework-specific).
        /// </summary>
        internal static string Debug_TargetFrameworkInfo_NotFrameworkSpecific {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_NotFrameworkSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt; PowerShell scripts are being executed from &apos;{0}&apos;{1}.
        /// </summary>
        internal static string Debug_TargetFrameworkInfo_PowershellScripts {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_PowershellScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For adding package &apos;{0}&apos; to project &apos;{1}&apos; that targets &apos;{2}&apos;..
        /// </summary>
        internal static string Debug_TargetFrameworkInfoPrefix {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependency &apos;{0}&apos; has invalid version specification..
        /// </summary>
        internal static string DependencyDoesNotHaveValidVersion {
            get {
                return ResourceManager.GetString("DependencyDoesNotHaveValidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot download packages from &apos;{0}&apos;..
        /// </summary>
        internal static string DownloadResourceNotFound {
            get {
                return ResourceManager.GetString("DownloadResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package stream for &apos;{0}&apos; cannot be found at &apos;{1}&apos;..
        /// </summary>
        internal static string DownloadStreamNotAvailable {
            get {
                return ResourceManager.GetString("DownloadStreamNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directory {0} does not exist..
        /// </summary>
        internal static string Error_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("Error_DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File {0} does not exist..
        /// </summary>
        internal static string Error_FileDoesNotExist {
            get {
                return ResourceManager.GetString("Error_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid restore input where RestorePackagesWithLockFile property is set to false but a packages lock file exists at {0}..
        /// </summary>
        internal static string Error_InvalidLockFileInput {
            get {
                return ResourceManager.GetString("Error_InvalidLockFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package content hash validation failed for {0}. The package is different than the last restore..
        /// </summary>
        internal static string Error_PackageValidationFailed {
            get {
                return ResourceManager.GetString("Error_PackageValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The packages lock file is inconsistent with the project dependencies so restore can&apos;t be run in locked mode. Run restore without using restore locked mode to update the lock file..
        /// </summary>
        internal static string Error_RestoreInLockedModePackagesConfig {
            get {
                return ResourceManager.GetString("Error_RestoreInLockedModePackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while reading file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorLoadingPackagesConfig {
            get {
                return ResourceManager.GetString("ErrorLoadingPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while writing file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorWritingPackagesConfig {
            get {
                return ResourceManager.GetString("ErrorWritingPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find package &apos;{0}&apos; at source &apos;{1}&apos;..
        /// </summary>
        internal static string Exception_PackageNotFound {
            get {
                return ResourceManager.GetString("Exception_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception Type.
        /// </summary>
        internal static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception &apos;{0}&apos; thrown when trying to add source &apos;{1}&apos;. Please verify all your online package sources are available..
        /// </summary>
        internal static string ExceptionWhenTryingToAddSource {
            get {
                return ResourceManager.GetString("ExceptionWhenTryingToAddSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File &apos;{0}&apos; already exists in project &apos;{1}&apos;. Do you want to overwrite it?.
        /// </summary>
        internal static string FileConflictMessage {
            get {
                return ResourceManager.GetString("FileConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Found package &apos;{0} {1}&apos; in &apos;{2}&apos;..
        /// </summary>
        internal static string FoundPackageInPackagesFolder {
            get {
                return ResourceManager.GetString("FoundPackageInPackagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gathering dependency information took {0}.
        /// </summary>
        internal static string GatherTotalTime {
            get {
                return ResourceManager.GetString("GatherTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwriting existing file &apos;{0}&apos;...
        /// </summary>
        internal static string Info_OverwritingExistingFile {
            get {
                return ResourceManager.GetString("Info_OverwritingExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installed package &apos;{0}&apos; to project.
        /// </summary>
        internal static string InstalledPackage {
            get {
                return ResourceManager.GetString("InstalledPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installing package &apos;{0}&apos; to project.
        /// </summary>
        internal static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; cannot be called on a NullSettings. This may be caused on account of insufficient permissions to read or write to &apos;%AppData%\NuGet\NuGet.config&apos;.
        /// </summary>
        internal static string InvalidNullSettingsOperation {
            get {
                return ResourceManager.GetString("InvalidNullSettingsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to determine the project name for &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidProjectName {
            get {
                return ResourceManager.GetString("InvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When updating multiple packages, dependency behavior has to be DependencyBehavior.Highest.
        /// </summary>
        internal static string MultiplePackageInstallOrUpdateHasToBeAnUpdate {
            get {
                return ResourceManager.GetString("MultiplePackageInstallOrUpdateHasToBeAnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; has multiple package types, which is not supported..
        /// </summary>
        internal static string MultiplePackageTypesNotSupported {
            get {
                return ResourceManager.GetString("MultiplePackageTypesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already referencing a newer version of &apos;{0}&apos;...
        /// </summary>
        internal static string NewerVersionAlreadyReferenced {
            get {
                return ResourceManager.GetString("NewerVersionAlreadyReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid!! Could not find a folder under artifact type &apos;{0}&apos;, so cannot request for artifacts specific to target framework &apos;{1}&apos;.
        /// </summary>
        internal static string NoFolderSpecificToTargetFxFound {
            get {
                return ResourceManager.GetString("NoFolderSpecificToTargetFxFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No latest version found for &apos;{0}&apos; for the given source repositories and resolution context.
        /// </summary>
        internal static string NoLatestVersionFound {
            get {
                return ResourceManager.GetString("NoLatestVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No NuGetProject is available with specified name &apos;{0}&apos;.
        /// </summary>
        internal static string NoNuGetProjectWithSpecifiedName {
            get {
                return ResourceManager.GetString("NoNuGetProjectWithSpecifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No packages were found in packages.config for project &apos;{0}&apos;..
        /// </summary>
        internal static string NoPackagesInProject {
            get {
                return ResourceManager.GetString("NoPackagesInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No package updates are available from the current package source for project &apos;{0}&apos;..
        /// </summary>
        internal static string NoPackageUpdates {
            get {
                return ResourceManager.GetString("NoPackageUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no new updates available..
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Executing nuget actions took {0}.
        /// </summary>
        internal static string NugetActionsTotalTime {
            get {
                return ResourceManager.GetString("NugetActionsTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NuGetProject does not have &apos;Name&apos; set in metadata. It should be set and it should be unique.
        /// </summary>
        internal static string NuGetProjectDoesNotHaveName {
            get {
                return ResourceManager.GetString("NuGetProjectDoesNotHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more packages not found.
        /// </summary>
        internal static string OneOrMorePackagesNotFound {
            get {
                return ResourceManager.GetString("OneOrMorePackagesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; already exists in folder &apos;{1}&apos;.
        /// </summary>
        internal static string PackageAlreadyExistsInFolder {
            get {
                return ResourceManager.GetString("PackageAlreadyExistsInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; already exists in &apos;{1}&apos;.
        /// </summary>
        internal static string PackageAlreadyExistsInPackagesConfig {
            get {
                return ResourceManager.GetString("PackageAlreadyExistsInPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; already exists in project &apos;{1}&apos;.
        /// </summary>
        internal static string PackageAlreadyExistsInProject {
            get {
                return ResourceManager.GetString("PackageAlreadyExistsInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting package &apos;{0}&apos; from source &apos;{1}&apos; was cancelled..
        /// </summary>
        internal static string PackageCancelledFromSource {
            get {
                return ResourceManager.GetString("PackageCancelledFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; could not be installed.
        /// </summary>
        internal static string PackageCouldNotBeInstalled {
            get {
                return ResourceManager.GetString("PackageCouldNotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; does not exist in folder &apos;{1}&apos;.
        /// </summary>
        internal static string PackageDoesNotExistInFolder {
            get {
                return ResourceManager.GetString("PackageDoesNotExistInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; does not exist in project &apos;{1}&apos;.
        /// </summary>
        internal static string PackageDoesNotExistInProject {
            get {
                return ResourceManager.GetString("PackageDoesNotExistInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; does not exists in &apos;{1}&apos;.
        /// </summary>
        internal static string PackageDoesNotExisttInPackagesConfig {
            get {
                return ResourceManager.GetString("PackageDoesNotExisttInPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to uninstall &apos;{0}&apos; because &apos;{1}&apos; depends on it..
        /// </summary>
        internal static string PackageHasDependent {
            get {
                return ResourceManager.GetString("PackageHasDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to uninstall &apos;{0}&apos; because &apos;{1}&apos; depend on it..
        /// </summary>
        internal static string PackageHasDependents {
            get {
                return ResourceManager.GetString("PackageHasDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; is not found.
        /// </summary>
        internal static string PackageNotFound {
            get {
                return ResourceManager.GetString("PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; is not found in the following primary source(s): &apos;{1}&apos;. Please verify all your online package sources are available (OR) package id, version are specified correctly..
        /// </summary>
        internal static string PackageNotFoundInPrimarySources {
            get {
                return ResourceManager.GetString("PackageNotFoundInPrimarySources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; is not found on source &apos;{1}&apos;..
        /// </summary>
        internal static string PackageNotFoundOnSource {
            get {
                return ResourceManager.GetString("PackageNotFoundOnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve &apos;{0}&apos;. An additional constraint &apos;{1}&apos; defined in {2} prevents this operation..
        /// </summary>
        internal static string PackagesConfigAllowedVersionConflict {
            get {
                return ResourceManager.GetString("PackagesConfigAllowedVersionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applying constraint &apos;{0}&apos; defined in &apos;{1}&apos;..
        /// </summary>
        internal static string PackagesConfigAllowedVersions {
            get {
                return ResourceManager.GetString("PackagesConfigAllowedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Packages could not be installed.
        /// </summary>
        internal static string PackagesCouldNotBeInstalled {
            get {
                return ResourceManager.GetString("PackagesCouldNotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package stream should be seekable.
        /// </summary>
        internal static string PackageStreamShouldBeSeekable {
            get {
                return ResourceManager.GetString("PackageStreamShouldBeSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; to be uninstalled could not be found in project &apos;{1}&apos;.
        /// </summary>
        internal static string PackageToBeUninstalledCouldNotBeFound {
            get {
                return ResourceManager.GetString("PackageToBeUninstalledCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameter cannot be zero or negative.
        /// </summary>
        internal static string ParameterCannotBeZeroOrNegative {
            get {
                return ResourceManager.GetString("ParameterCannotBeZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The operation failed as details for project {0} could not be loaded..
        /// </summary>
        internal static string ProjectNotLoaded_RestoreFailed {
            get {
                return ResourceManager.GetString("ProjectNotLoaded_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed package &apos;{0}&apos; from folder &apos;{1}&apos;.
        /// </summary>
        internal static string RemovedPackageFromFolder {
            get {
                return ResourceManager.GetString("RemovedPackageFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed package &apos;{0}&apos; from project &apos;{1}&apos;.
        /// </summary>
        internal static string RemovedPackageFromMSBuildProject {
            get {
                return ResourceManager.GetString("RemovedPackageFromMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed package &apos;{0}&apos; from &apos;{1}&apos;.
        /// </summary>
        internal static string RemovedPackageFromPackagesConfig {
            get {
                return ResourceManager.GetString("RemovedPackageFromPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing package &apos;{0}&apos; from folder &apos;{1}&apos;.
        /// </summary>
        internal static string RemovingPackageFromFolder {
            get {
                return ResourceManager.GetString("RemovingPackageFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing package &apos;{0}&apos; from project &apos;{1}&apos;.
        /// </summary>
        internal static string RemovingPackageFromMSBuildProject {
            get {
                return ResourceManager.GetString("RemovingPackageFromMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolution was successful but resulted in no action.
        /// </summary>
        internal static string ResolutionSuccessfulNoAction {
            get {
                return ResourceManager.GetString("ResolutionSuccessfulNoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolved actions to install package &apos;{0}&apos;.
        /// </summary>
        internal static string ResolvedActionsToInstallPackage {
            get {
                return ResourceManager.GetString("ResolvedActionsToInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolved actions to uninstall package &apos;{0}&apos;.
        /// </summary>
        internal static string ResolvedActionsToUninstallPackage {
            get {
                return ResourceManager.GetString("ResolvedActionsToUninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolving actions install multiple packages.
        /// </summary>
        internal static string ResolvingActionsToInstallOrUpdateMultiplePackages {
            get {
                return ResourceManager.GetString("ResolvingActionsToInstallOrUpdateMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolving actions to install package &apos;{0}&apos;.
        /// </summary>
        internal static string ResolvingActionsToInstallPackage {
            get {
                return ResourceManager.GetString("ResolvingActionsToInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolving actions to uninstall package &apos;{0}&apos;.
        /// </summary>
        internal static string ResolvingActionsToUninstallPackage {
            get {
                return ResourceManager.GetString("ResolvingActionsToUninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package restore failed. Rolling back package changes for &apos;{0}&apos;..
        /// </summary>
        internal static string RestoreFailedRollingBack {
            get {
                return ResourceManager.GetString("RestoreFailedRollingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restoring NuGet package {0}..
        /// </summary>
        internal static string RestoringPackage {
            get {
                return ResourceManager.GetString("RestoringPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieving package &apos;{0} {1}&apos; from &apos;{2}&apos;..
        /// </summary>
        internal static string RetrievingPackageStart {
            get {
                return ResourceManager.GetString("RetrievingPackageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signed package validation failed with multiple errors:{0}.
        /// </summary>
        internal static string SignatureVerificationMultiple {
            get {
                return ResourceManager.GetString("SignatureVerificationMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solution directory &apos;{0}&apos; must be a rooted path..
        /// </summary>
        internal static string SolutionDirectoryMustBeRooted {
            get {
                return ResourceManager.GetString("SolutionDirectoryMustBeRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solution is not opened or not saved. Please ensure you have an open and saved solution..
        /// </summary>
        internal static string SolutionDirectoryNotAvailable {
            get {
                return ResourceManager.GetString("SolutionDirectoryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uninstall is not supported when SolutionManager is not available.
        /// </summary>
        internal static string SolutionManagerNotAvailableForUninstall {
            get {
                return ResourceManager.GetString("SolutionManagerNotAvailableForUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully installed &apos;{0}&apos; to {1}.
        /// </summary>
        internal static string SuccessfullyInstalled {
            get {
                return ResourceManager.GetString("SuccessfullyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully uninstalled &apos;{0}&apos; from {1}.
        /// </summary>
        internal static string SuccessfullyUninstalled {
            get {
                return ResourceManager.GetString("SuccessfullyUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The replacement token &apos;{0}&apos; has no value.
        /// </summary>
        internal static string TokenHasNoValue {
            get {
                return ResourceManager.GetString("TokenHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not install package &apos;{0}&apos;. You are trying to install this package into a project that targets &apos;{1}&apos;, but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author..
        /// </summary>
        internal static string UnableToFindCompatibleItems {
            get {
                return ResourceManager.GetString("UnableToFindCompatibleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to gather dependency information for package &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToGatherDependencyInfo {
            get {
                return ResourceManager.GetString("UnableToGatherDependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to gather dependency information for multiple packages.
        /// </summary>
        internal static string UnableToGatherDependencyInfoForMultiplePackages {
            get {
                return ResourceManager.GetString("UnableToGatherDependencyInfoForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to gather package &apos;{0}&apos; from source &apos;{1}&apos;. Please verify all your online package sources are available. .
        /// </summary>
        internal static string UnableToGatherPackageFromSource {
            get {
                return ResourceManager.GetString("UnableToGatherPackageFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve dependencies for package &apos;{0}&apos; with DependencyBehavior &apos;{1}&apos;.
        /// </summary>
        internal static string UnableToResolveDependencyInfo {
            get {
                return ResourceManager.GetString("UnableToResolveDependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve dependencies for multiple packages.
        /// </summary>
        internal static string UnableToResolveDependencyInfoForMultiplePackages {
            get {
                return ResourceManager.GetString("UnableToResolveDependencyInfoForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find package &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownPackage {
            get {
                return ResourceManager.GetString("UnknownPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find version &apos;{1}&apos; of package &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownPackageSpecificVersion {
            get {
                return ResourceManager.GetString("UnknownPackageSpecificVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source &apos;{0}&apos; not found. Please provide an HTTP or local source..
        /// </summary>
        internal static string UnknownSource {
            get {
                return ResourceManager.GetString("UnknownSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsupported type of source &apos;{0}&apos;. Please provide an HTTP or local source..
        /// </summary>
        internal static string UnknownSourceType {
            get {
                return ResourceManager.GetString("UnknownSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find package &apos;{0}&apos; at source &apos;{1}&apos;. Source not found..
        /// </summary>
        internal static string UnknownSourceWithId {
            get {
                return ResourceManager.GetString("UnknownSourceWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; uses features that are not supported by the current version of NuGet. To upgrade NuGet, see https://docs.nuget.org/consume/installing-nuget.
        /// </summary>
        internal static string UnsupportedPackageFeature {
            get {
                return ResourceManager.GetString("UnsupportedPackageFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package &apos;{0}&apos; has a package type &apos;{1}&apos; that is not supported by project &apos;{2}&apos;..
        /// </summary>
        internal static string UnsupportedPackageType {
            get {
                return ResourceManager.GetString("UnsupportedPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directory &apos;{0}&apos; is not empty. Skipping....
        /// </summary>
        internal static string Warning_DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("Warning_DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error finding repository for &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Warning_ErrorFindingRepository {
            get {
                return ResourceManager.GetString("Warning_ErrorFindingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; already exists. Skipping....
        /// </summary>
        internal static string Warning_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Warning_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skipping &apos;{0}&apos; because it was modified..
        /// </summary>
        internal static string Warning_FileModified {
            get {
                return ResourceManager.GetString("Warning_FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Install failed. Rolling back....
        /// </summary>
        internal static string Warning_RollingBack {
            get {
                return ResourceManager.GetString("Warning_RollingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while applying transformation to &apos;{0}&apos; in project &apos;{1}&apos;.
        /// </summary>
        internal static string XdtError {
            get {
                return ResourceManager.GetString("XdtError", resourceCulture);
            }
        }
    }
}
