//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Frameworks {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stride.Core.NuGet.NuGet.Frameworks.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The argument cannot be null or empty..
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TargetPlatformIdentifier is only supported on .NET 5.0 and above..
        /// </summary>
        internal static string FrameworkDoesNotSupportPlatforms {
            get {
                return ResourceManager.GetString("FrameworkDoesNotSupportPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .NET 5.0 and above does not support profiles..
        /// </summary>
        internal static string FrameworkDoesNotSupportProfiles {
            get {
                return ResourceManager.GetString("FrameworkDoesNotSupportProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frameworks must have the same identifier, profile, and platform..
        /// </summary>
        internal static string FrameworkMismatch {
            get {
                return ResourceManager.GetString("FrameworkMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid framework identifier &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidFrameworkIdentifier {
            get {
                return ResourceManager.GetString("InvalidFrameworkIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid framework version &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidFrameworkVersion {
            get {
                return ResourceManager.GetString("InvalidFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid platform version &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidPlatformVersion {
            get {
                return ResourceManager.GetString("InvalidPlatformVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid portable frameworks &apos;{0}&apos;. A hyphen may not be in any of the portable framework names..
        /// </summary>
        internal static string InvalidPortableFrameworksDueToHyphen {
            get {
                return ResourceManager.GetString("InvalidPortableFrameworksDueToHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid portable frameworks for &apos;{0}&apos;. A portable framework must have at least one framework in the profile..
        /// </summary>
        internal static string MissingPortableFrameworks {
            get {
                return ResourceManager.GetString("MissingPortableFrameworks", resourceCulture);
            }
        }
    }
}
