//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.Resolver {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stride.Core.NuGet.NuGet.Resolver.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circular dependency detected &apos;{0}&apos;..
        /// </summary>
        internal static string CircularDependencyDetected {
            get {
                return ResourceManager.GetString("CircularDependencyDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a constraint.
        /// </summary>
        internal static string DependencyConstraint {
            get {
                return ResourceManager.GetString("DependencyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The package &apos;{0}&apos; version &apos;{1}&apos; declared a duplicate dependency &apos;{2}&apos;. This might mean the package is corrupt or the server metadata for the package is corrupt..
        /// </summary>
        internal static string DuplicateDependencyIdsError {
            get {
                return ResourceManager.GetString("DuplicateDependencyIdsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A fatal error occured while resolving dependencies..
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: {0}.
        /// </summary>
        internal static string InvalidPackageConfig {
            get {
                return ResourceManager.GetString("InvalidPackageConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find package &apos;{0}&apos;. Existing packages must be restored before performing an install or update..
        /// </summary>
        internal static string MissingDependencyInfo {
            get {
                return ResourceManager.GetString("MissingDependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve dependencies..
        /// </summary>
        internal static string NoSolution {
            get {
                return ResourceManager.GetString("NoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; has an additional constraint {1} defined in {2}..
        /// </summary>
        internal static string PackagesConfigConstraint {
            get {
                return ResourceManager.GetString("PackagesConfigConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolving dependency information took {0}.
        /// </summary>
        internal static string ResolverTotalTime {
            get {
                return ResourceManager.GetString("ResolverTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find a version of &apos;{0}&apos; that is compatible with {1}..
        /// </summary>
        internal static string UnableToFindCompatibleVersion {
            get {
                return ResourceManager.GetString("UnableToFindCompatibleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve dependency &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToResolveDependencyForEmptySource {
            get {
                return ResourceManager.GetString("UnableToResolveDependencyForEmptySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve dependency &apos;{0}&apos;. Source(s) used: {1}..
        /// </summary>
        internal static string UnableToResolveDependencyForMultipleSources {
            get {
                return ResourceManager.GetString("UnableToResolveDependencyForMultipleSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown DependencyBehavior value..
        /// </summary>
        internal static string UnknownDependencyBehavior {
            get {
                return ResourceManager.GetString("UnknownDependencyBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to resolve dependencies. &apos;{0}&apos; is not compatible with {1}..
        /// </summary>
        internal static string VersionIsNotCompatible {
            get {
                return ResourceManager.GetString("VersionIsNotCompatible", resourceCulture);
            }
        }
    }
}
